# ROSbridge websocket server info
rosbridge_ip: rap-2022-ws-staff-toff.k8s.init-lab.ch #rosbridge.k8sbeta.init-lab.ch #172.17.0.1
rosbridge_port: 443 #9090
use_wss: true
# Topics being published remotely to expose locally
remote_topics:
     [
          ['/niryo_one_follow_joint_trajectory_controller/command', 'trajectory_msgs/JointTrajectory', 'cc', false, 50],
          ['/niryo_one_follow_joint_trajectory_controller/follow_joint_trajectory/cancel', 'actionlib_msgs/GoalID', 'cancel', false, 50],
          ['/niryo_one_follow_joint_trajectory_controller/follow_joint_trajectory/goal', 'control_msgs/FollowJointTrajectoryActionGoal', 'goal', false, 50],
          #["/summit_xl/joint_states", "sensor_msgs/JointState"],
          #["/tf", "tf2_msgs/TFMessage"],
          #["/tf_static", "tf2_msgs/TFMessage"],
          #["/text", "std_msgs/String"],
          #["/summit_xl/arm_camera/depth_registered/points", "sensor_msgs/PointCloud2", "/summit_xl/arm_camera/depth_registered/points", false, 5000],
     ]

# Topics being published in the local roscore to expose remotely
all_local_topics: false
local_topics: [
              ['/niryo_one_follow_joint_trajectory_controller/follow_joint_trajectory/feedback', 'control_msgs/FollowJointTrajectoryActionFeedback', 'feed', false, 50],
              ['/niryo_one_follow_joint_trajectory_controller/follow_joint_trajectory/result', 'control_msgs/FollowJointTrajectoryActionResult', 'result', false, 50],
              ['/niryo_one_follow_joint_trajectory_controller/follow_joint_trajectory/status', 'actionlib_msgs/GoalStatusArray', 'status', false, 50],
              ['/joint_states', 'sensor_msgs/JointState'],
              ['/niryo_one_follow_joint_trajectory_controller/state', 'control_msgs/JointTrajectoryControllerState', 'cs', false, 50],
              #["/text_2", "std_msgs/String"],
              #['/camera/depth_registered/points', 'sensor_msgs/PointCloud2', "pc", false, 10000],
              ['/camera/color/image_raw/compressed', 'sensor_msgs/CompressedImage', 'aaa', false, 500],
              #['/camera/depth/image_rect_raw/compressed', 'sensor_msgs/CompressedImage', 'bbb', false, 1000],
# ['/tf_static', 'tf2_msgs/TFMessage'],
# ['/tf', 'tf2_msgs/TFMessage'],
            ]
# Services running remotely to expose locally
remote_services: [["/rosapi/topics", "rosapi/Topics"]]
# ["/rosapi/get_param", "rosapi/GetParam"],
# Services running locally to expose remotely
local_services: [
  ["/controller_manager/list_controllers", "controller_manager_msgs/ListControllers"],
#["/map_saver/get_loggers", "roscpp/GetLoggers"]
]
# Parameters to be sync, they will be polled to stay in sync
parameters: [] #["/summit_xl/robot_description"]
parameter_polling_hz: 0.03
